/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    CssStyle: typeof import('./src/components/CssStyle.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InslineStyle: typeof import('./src/components/InslineStyle.vue')['default']
    TransitionBasic: typeof import('./src/components/TransitionBasic.vue')['default']
  }
}
